# Site settings
title: Paul Sonnentag
email: "paul.sonnentag@googlemail.com"
url: "paulsonnentag.com"
twitter_username: paulsonnentag
github_username:  paulsonnentag
permalink: /:title

sass:
    sass_dir: _sass
    style: :compressed

# Build settings
markdown: kramdown
